name: 'Cypress tests Dockerfile generator'
description: 'Generate Cypress included Dockerfile to build an image with your tests'
inputs:
  context:
    description: 'Cypress folder'
    required: true
    default: '.'
  dockerfile:
    description: 'Dockerfile name'
    required: true
    default: 'Dockerfile'
  cypress_version:
    description: 'Cypress version'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.context }}
    - ${{ inputs.dockerfile }}
    - ${{ inputs.cypress_version }}
